import * as kv from "./kv_store.tsx";

/**
 * Seed fan contributions data
 */
export async function seedContributions() {
  console.log("🎨 Seeding fan contributions...");

  const contributions = [
    {
      id: crypto.randomUUID(),
      type: 'tattoo',
      image: 'https://images.unsplash.com/photo-1761957360313-3e63d01415a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YXR0b28lMjBhcnQlMjBkYXJrfGVufDF8fHx8MTc2OTAyNTAyOXww&ixlib=rb-4.1.0&q=80&w=1080',
      author: '@darkside_ink',
      authorId: null,
      likes: 342,
      comments: 28,
      caption: 'Mon nouveau tattoo Korn #UntouchablesFR',
      legend: 'Encre & Peau',
      subtitle: 'Les plus beaux tatouages Korn.',
      status: 'approved',
      submittedAt: new Date('2026-03-15').toISOString(),
      approvedAt: new Date('2026-03-16').toISOString(),
      approvedBy: 'admin',
      featured: true,
      tags: ['tattoo', 'art'],
    },
    {
      id: crypto.randomUUID(),
      type: 'art',
      image: 'https://images.unsplash.com/photo-1759302307377-e72f6a6918a1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYW4lMjBhcnQlMjBkcmF3aW5nfGVufDF8fHx8MTc2OTAyNTAyOXww&ixlib=rb-4.1.0&q=80&w=1080',
      author: '@kornartiist',
      authorId: null,
      likes: 589,
      comments: 45,
      caption: 'Fan art Jonathan Davis #UntouchablesFR',
      legend: 'Fan-Arts',
      subtitle: 'Dessins et créations numériques.',
      status: 'approved',
      submittedAt: new Date('2026-03-18').toISOString(),
      approvedAt: new Date('2026-03-18').toISOString(),
      approvedBy: 'admin',
      featured: true,
      tags: ['fanart', 'drawing'],
    },
    {
      id: crypto.randomUUID(),
      type: 'collection',
      image: 'https://images.unsplash.com/photo-1616663395731-d70897355fd8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aW55bCUyMGNvbGxlY3Rpb258ZW58MXx8fHwxNzY4OTgwNjQwfDA&ixlib=rb-4.1.0&q=80&w=1080',
      author: '@vinyl_collector',
      authorId: null,
      likes: 234,
      comments: 19,
      caption: 'Ma collection Korn complète #UntouchablesFR',
      legend: 'Collectors',
      subtitle: 'Vinyles rares et éditions limitées.',
      status: 'approved',
      submittedAt: new Date('2026-03-10').toISOString(),
      approvedAt: new Date('2026-03-11').toISOString(),
      approvedBy: 'admin',
      featured: true,
      tags: ['vinyl', 'collection'],
    },
    {
      id: crypto.randomUUID(),
      type: 'memorabilia',
      image: 'https://images.unsplash.com/photo-1759835715024-11684a8109e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb25jZXJ0JTIwbWVtb3JhYmlsaWF8ZW58MXx8fHwxNzY5MDI1MDMwfDA&ixlib=rb-4.1.0&q=80&w=1080',
      author: '@korn_memories',
      authorId: null,
      likes: 412,
      comments: 31,
      caption: 'Souvenirs du concert Paris 2024 #UntouchablesFR',
      legend: 'Souvenirs Live',
      subtitle: 'Setlists, mediators et photos de fosse.',
      status: 'approved',
      submittedAt: new Date('2026-03-20').toISOString(),
      approvedAt: new Date('2026-03-20').toISOString(),
      approvedBy: 'admin',
      featured: true,
      tags: ['concert', 'memorabilia'],
    },
    {
      id: crypto.randomUUID(),
      type: 'tattoo',
      image: 'https://images.unsplash.com/photo-1565058379802-bbe93b2f703a?w=800&q=80',
      author: '@ink_master',
      authorId: null,
      likes: 178,
      comments: 12,
      caption: 'Korn logo sur l\'avant-bras #UntouchablesFR',
      legend: 'Encre & Peau',
      subtitle: 'Les plus beaux tatouages Korn.',
      status: 'approved',
      submittedAt: new Date('2026-03-12').toISOString(),
      approvedAt: new Date('2026-03-13').toISOString(),
      approvedBy: 'admin',
      featured: false,
      tags: ['tattoo', 'logo'],
    },
    {
      id: crypto.randomUUID(),
      type: 'art',
      image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80',
      author: '@digital_artist',
      authorId: null,
      likes: 445,
      comments: 38,
      caption: 'Portrait digital de Fieldy #UntouchablesFR',
      legend: 'Fan-Arts',
      subtitle: 'Dessins et créations numériques.',
      status: 'approved',
      submittedAt: new Date('2026-03-14').toISOString(),
      approvedAt: new Date('2026-03-15').toISOString(),
      approvedBy: 'admin',
      featured: false,
      tags: ['fanart', 'digital', 'fieldy'],
    },
    {
      id: crypto.randomUUID(),
      type: 'collection',
      image: 'https://images.unsplash.com/photo-1619983081593-e2ba5b543168?w=800&q=80',
      author: '@cd_collector',
      authorId: null,
      likes: 156,
      comments: 9,
      caption: 'Toutes les éditions de Follow The Leader #UntouchablesFR',
      legend: 'Collectors',
      subtitle: 'CD rares et éditions limitées.',
      status: 'approved',
      submittedAt: new Date('2026-03-08').toISOString(),
      approvedAt: new Date('2026-03-09').toISOString(),
      approvedBy: 'admin',
      featured: false,
      tags: ['cd', 'collection', 'ftl'],
    },
    {
      id: crypto.randomUUID(),
      type: 'memorabilia',
      image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
      author: '@live_fan',
      authorId: null,
      likes: 289,
      comments: 22,
      caption: 'Setlist autographiée Hellfest 2025 #UntouchablesFR',
      legend: 'Souvenirs Live',
      subtitle: 'Setlists, médiators et photos de fosse.',
      status: 'approved',
      submittedAt: new Date('2026-03-17').toISOString(),
      approvedAt: new Date('2026-03-17').toISOString(),
      approvedBy: 'admin',
      featured: false,
      tags: ['setlist', 'hellfest', 'autograph'],
    },
  ];

  for (const contribution of contributions) {
    await kv.set(`contribution:${contribution.id}`, contribution);
  }

  console.log(`✅ ${contributions.length} contributions seeded`);
}
